id: I71E419A5
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:52:10.082474
last_modified: 2023-02-09 14:52:10.082623
source_metadata:
  title: 'PP: Vajracchedikā Prajñāpāramitā'
  language: zh
bases:
  '2505':
    base_file: 2505.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
